MONGO_DB_USER_NAME: test_user
MONGO_DB_PASSWORD: test_password
MONGO_DB_NAME: test_database
MONGO_DB_HOST: localhost
MONGO_DB_PORT: 27017
MONGO_DB_URI: mongodb://${MONGO_DB_USER_NAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/?authMechanism=SCRAM-SHA-1&authSource=${MONGO_DB_NAME}

spring:
  data:
    mongodb:
#      port: ${MONGO_DB_PORT}
#      host: ${MONGO_DB_HOST}
#      username: ${MONGO_DB_USER_NAME}
#      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB_NAME}
      uri: ${MONGO_DB_URI}
#      uri:  #mongodb://test_user:test_password@localhost:27017/?authMechanism=SCRAM-SHA-1&authSource=test_database
